### ISSUE TITLE
Maven build fails testing rt-processor

### ISSUE THREAD

**Issue by ghost** [horovits/rt-analytics#3]
I'm getting the following error while trying to build latest rt-analytics:

Tests in error: 
  saveTwoCountersAndRequestAll(org.openspaces.bigdata.processor.WriteLocalCountBulkTest): Failed to load ApplicationContext
  saveTwoCountersButRequestOnlyFoo(org.openspaces.bigdata.processor.WriteLocalCountBulkTest): Failed to load ApplicationContext

I'm new to Maven so I'm not quite sure how to fix this.

Cheers,
Dave

**Comment by uric** [comment]
HI Dave

The updated repo may be found here: https://github.com/Gigaspaces/rt-analytics, where the build should be up to date and work properly. 
You can also find a detailed tutorial for this app here: http://www.gigaspaces.com/wiki/display/XAP9/Writing+a+Real+Time+Analytics+for+Big+Data+Application

**Comment by ghost** [comment]
Hi Uri:

Perfect, thanks.

Cheers,
Dave

**Comment by ghost** [comment]
Hi Uri:

Just on a side note - do you guys have any more PHP examples besides the 
one at openspaces.org? I'm pretty excited about scaling PHP on your 
platform. I won't ask any more questions on this thread :-)

Cheers,
Dave

**Comment by uric** [comment]
Hi Dave 

Sorry, only spotted this comment now. The only example I'm aware of is the one you mentioned. However XAP does also have a [REST API](https://github.com/OpenSpaces/RESTData) and a [Memcached API](http://www.gigaspaces.com/wiki/display/XAP9/The+Memcached+API) which you can use from PHP. 

HTH, 
Uri

**Comment by ghost** [comment]
Hi Uri:

Thanks - I'll check this out....

Cheers,
Dave

**Comment by dotanh** [comment]
Thanks Uri for the updates.
I pulled in the changes from Gigaspaces fork to avoid future confusion.
